package app.trimgallery.feature.gallery

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.unit.dp
import app.trimgallery.core.model.Job
import app.trimgallery.core.model.MediaItem
import app.trimgallery.core.ui.format.MediaFormatting
import app.trimgallery.core.ui.motion.MotionSpec
import app.trimgallery.core.ui.motion.pressScale
import app.trimgallery.core.ui.theme.TrimTheme

/** One action along the bottom of the viewer. */
data class ViewerAction(val label: String, val selected: Boolean = false, val onClick: () -> Unit)

/**
 * The viewer's info sheet (BUILD.md § 9).
 *
 * Carries the facts the user came for — date, camera, place — and the one fact only this
 * app can tell them: `"Optimised · was 380 MB, now 165 MB"`.
 *
 * That line is generated by [MediaFormatting], which returns null when the item was never
 * optimised or did not actually shrink, so the sheet cannot claim a saving that did not
 * happen. PROJECT.md is emphatic that the app must never overstate what it did, and this
 * is the screen where overstating would be easiest.
 */
@Composable
fun ViewerInfoSheet(
    item: MediaItem,
    job: Job?,
    modifier: Modifier = Modifier,
    capturedOn: String? = null,
    place: String? = null,
    actions: List<ViewerAction> = emptyList(),
) {
    val colors = TrimTheme.colors
    val optimised = MediaFormatting.optimisedLine(job?.originalSize, job?.newSize)

    Column(
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(topStart = MotionSpec.Sheet.CORNER_RADIUS_DP.dp, topEnd = MotionSpec.Sheet.CORNER_RADIUS_DP.dp))
            .background(colors.band)
            .padding(horizontal = PADDING_H_DP.dp, vertical = PADDING_V_DP.dp),
        verticalArrangement = Arrangement.spacedBy(ROW_GAP_DP.dp),
    ) {
        BasicText(
            text = item.name,
            style = TrimTheme.typography.label.copy(color = colors.text),
        )

        capturedOn?.let { InfoRow(it) }
        item.cameraModel?.let { InfoRow(it) }
        place?.let { InfoRow(it) }

        InfoRow(
            buildString {
                append(MediaFormatting.bytes(item.size))
                if (item.width > 0 && item.height > 0) append(" · ${item.width} × ${item.height}")
                item.duration?.let { append(" · ${MediaFormatting.duration(it)}") }
            },
        )

        if (optimised != null) {
            // The one line the user reads this sheet for; given the accent so it reads
            // as this app's contribution rather than another file property.
            BasicText(
                text = optimised,
                style = TrimTheme.typography.label.copy(color = colors.accent),
            )
        }

        if (actions.isNotEmpty()) {
            Row(
                modifier = Modifier.fillMaxWidth().padding(top = ACTIONS_TOP_DP.dp),
                horizontalArrangement = Arrangement.spacedBy(GAP_DP.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                actions.forEach { action ->
                    Box(
                        Modifier
                            .clip(RoundedCornerShape(percent = HALF))
                            .background(if (action.selected) colors.accent else colors.card)
                            .pressScale(action.onClick)
                            .padding(horizontal = ACTION_H_DP.dp, vertical = ACTION_V_DP.dp),
                    ) {
                        BasicText(
                            text = action.label,
                            style = TrimTheme.typography.caption.copy(
                                color = if (action.selected) colors.page else colors.text,
                            ),
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun InfoRow(text: String) {
    BasicText(text = text, style = TrimTheme.typography.caption.copy(color = TrimTheme.colors.muted))
}

/**
 * The standard action row. An action keeps the same name through the whole flow, so
 * "Favourite" toggles to a selected "Favourite" rather than becoming "Unfavourite".
 */
fun viewerActions(
    item: MediaItem,
    onFavourite: () -> Unit,
    onShare: () -> Unit,
    onEdit: () -> Unit,
    onDelete: () -> Unit,
): List<ViewerAction> = listOf(
    ViewerAction("Favourite", selected = item.favourite, onClick = onFavourite),
    ViewerAction("Share", onClick = onShare),
    ViewerAction("Edit", onClick = onEdit),
    // Delete moves the original to Recently deleted; it is not destructive here, and the
    // label should not imply otherwise anywhere it appears.
    ViewerAction("Delete", onClick = onDelete),
)

private const val PADDING_H_DP = 24
private const val PADDING_V_DP = 22
private const val ROW_GAP_DP = 4
private const val GAP_DP = 8
private const val ACTIONS_TOP_DP = 12
private const val ACTION_H_DP = 14
private const val ACTION_V_DP = 10
private const val HALF = 50
